/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/lib/themes/loyalty-theme.ts
 * Command: astryx theme build src/lib/themes/loyalty-theme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./loyalty.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const loyaltyTheme: DefinedTheme;
