/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/lib/themes/neo-brutalist-theme.ts
 * Command: astryx theme build src/lib/themes/neo-brutalist-theme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const neoBrutalistTheme: DefinedTheme;
