/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/loyaltyhub/loyaltyhubTheme.ts
 * Command: astryx theme build src/themes/loyaltyhub/loyaltyhubTheme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/// <reference path="./loyaltyhub.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const loyaltyhubIconRegistry: IconRegistry;
export declare const loyaltyhubTheme: DefinedTheme;
