/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/loyaltyhub/loyaltyhubTheme.ts
 * Command: astryx theme build src/themes/loyaltyhub/loyaltyhubTheme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/ProgressBar' {
  interface ProgressBarVariantMap {
    'orange': true;
    'yellow': true;
    'purple': true;
  }
}
